### PR TITLE
Load Balancer Using NODE.Js

### PR DESCRIPTION
**Pull request by Arpit529Srivastava**
issue #43 
resovled

This pull request introduces a simple load balancer along with two API services for handling books and movies. The changes include the implementation of the load balancer, the creation of two API services, and the necessary documentation and dependencies.

### Implementation of Load Balancer and API Services:

* **Load Balancer Implementation**:
  * [`Load_balancer/balancer.js`](diffhunk://#diff-c696ff67b05465aee05b76decfa75f3ae456c19343d4104981209ef0b18d8f03R1-R40): Created a load balancer using `http-proxy` to distribute requests between the books and movies API services using a round-robin algorithm.
  
* **Books API Service**:
  * [`Load_balancer/api1.js`](diffhunk://#diff-4e502dfb508b83d70f1386cc60e4d04672ad5c316d9c8d03c7ceb2832b372e41R1-R21): Implemented a simple Express server to handle book-related requests on port 3000.

* **Movies API Service**:
  * [`Load_balancer/api2.js`](diffhunk://#diff-030ef2a6a973361b1d5d629c273e32a810f94bc103e186489e9036a9323e8a77R1-R21): Implemented a simple Express server to handle movie-related requests on port 3001.

### Documentation and Dependencies:

* **Documentation**:
  * [`Load_balancer/README.md`](diffhunk://#diff-0fef1e2a3c453f01c2efda9bf9d642c89a9e9ce9fc8f993741f823bcc41d8ae3R1-R61): Added documentation explaining the project, including usage instructions, file descriptions, and details on the load balancing algorithm.

* **Dependencies**:
  * [`Load_balancer/package.json`](diffhunk://#diff-d2e0ab509d57719305cb45bc22704291786a8c2892b7df33f82b70d69ac96a0bR1-R16): Added `express` and `http-proxy` as dependencies required for the API services and load balancer.
  
  @manchicken please review this and add the label ```hacktoberfest-accepted```

### CODE REVIEW

**Comment by manchicken** [comment]
@Arpit529Srivastava: Could you help me understand how does this fit in with this library?

**Comment by Arpit529Srivastava** [comment]
users can learn about the basic of concurrency with this how routes are directed, how reverse proxy works etc.

**Comment by manchicken** [comment]
> users can learn about the basic of concurrency with this how routes are directed, how reverse proxy works etc.
> 
> 

Why do you think that this library is for that?

**Comment by Arpit529Srivastava** [comment]
the tag was mentioned ```concurrency``` so put the issue and was assigned to the work

**Comment by manchicken** [comment]
This is spam. The contributor neither adhered to the `CONTRIBUTING.md` nor did they bother to learn the purpose of the project.

Please do not submit spammy PRs, friends.

**Pull request closed without merging**
